--- $Id: dbinit.txt 1729 2006-11-12 23:03:16Z benalex $

--- Sample Hypersonic SQL compatible schema and data
---
--- All Acegi Security JDBC DAOs can be customised to use a different schema.
--- In addition, the Acegi Security JDBC DAOs do not even need to be used
--- with Acegi Security, and an entirely customised persistence strategy
--- can be employed via standard interfaces (eg in-memory, Hibernate etc).

SET IGNORECASE TRUE;

CREATE TABLE users (
   ID INTEGER generated by default as identity (start with 1) not null, 
	username VARCHAR(50) NOT NULL ,
	password VARCHAR(50) NOT NULL,
	enabled BIT NOT NULL,
	authority VARCHAR(50) NOT NULL
);


INSERT INTO users VALUES (1,'david', 'newyork', true,'ROLE_ADMIN');
INSERT INTO users VALUES (2,'alex', 'newjersey', true, 'ROLE_USER');
INSERT INTO users VALUES (3,'tim', 'illinois', true, 'ROLE_USER');
INSERT INTO users VALUES (4,'test', 'test', true,'ROLE_ADMIN');


